### ISSUE TITLE
training and testing script

### ISSUE THREAD

**Issue by qiqiguaitm** [isi-vista/face-completion#1]
when will release the training and testing script

**Comment by iacopomasi** [comment]
Hi @qiqiguaitm ,
thank you for being interested in our work. My coauthor @joemathai  and I are very busy with other work we are doing for different projects. We initially planned to release the trained model but we are behind schedule and we do not have this in our priorities for now.

If you need to know something, in particular, feel free to ask me but please expect a slow response. I did some a new related work about [face occlusion detection](https://arxiv.org/abs/1911.00957) you may want to consider--thanks

iacopo
