### ISSUE TITLE
how to make train data?

### ISSUE THREAD

**Issue by zhangxiaopang88** [isi-vista/face-completion#2]
Hello, I'm so glad to see your paper.Can you tell me how you make the data?

**Comment by iacopomasi** [comment]
Hi @zhangxiaopang88 ,
the code to make the training data is a bit complex in dependencies to be released and we do not have now time for it but it consists of different parts. First of all, you need to download some 3D object models to be able to place them on the face. (e.g. 3D model of sunglasses). You can use websites such as [this](https://free3d.com/3d-models/). Watch out that some of these models have proprietary licenses. 

Once you have the 3D model, what I did was to place in the same coordinate system of a 3D generic model. We used a 3D generic model from another project based on [FacePoseNet](https://free3d.com/3d-models/).

Once the 3D object model is aligned to the 3D generic face, you can estimate the 3D pose of a given input image using [FacePoseNet](https://free3d.com/3d-models/) wrt to the 3D generic face model and then render the 3D object onto the input image. You can customize the rendering to render the object texture or a random texture if you want.

For rendering, we used this GitHub project [face3d](https://free3d.com/3d-models/)

I hope this helps.
